project:
  type: website
  output-dir: docs

website:
  title: "Jeremy D. Hoffman"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lumen
    css: styles.css
    page-layout: full
    toc: true

editor: visual

