project:
  type: website
  output-dir: docs

website:
  title: "Jeremy D. Hoffman"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: "Jeremy_Hoffman_CV.pdf"
        text: CV
    right: 
      - icon: github
        href: https://www.github.com/jeremydhoffman
      - icon: twitter
        href: https://www.twitter.com/jeremydhoffman
        
  page-footer:
    left: "Copyright © 2023, Jeremy D. Hofmman"
  
format:
  html:
    theme: lumen
    css: styles.css
    page-layout: full
    toc: true

editor: visual

