project:
  type: website
  output-dir: docs

website:
  title: "Jeremy D. Hoffman"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: "Jeremy_Hoffman_CV.pdf"
        text: CV

format:
  html:
    theme: lumen
    css: styles.css
    page-layout: full
    toc: true

editor: visual

